# Generated by Django 4.0.5 on 2022-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Скоро здесь будет описание рецепта', verbose_name='Текст рецепта'),
        ),
    ]
