# Generated by Django 4.2.1 on 2023-06-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_site', '0007_userblog_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.CharField(blank=True, max_length=20, null=True)),
                ('github', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserBlog',
        ),
    ]
