# Generated by Django 4.2.1 on 2023-06-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_userprofile_delete_userblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
